version: "3"

services:

  mongo-express:
    container_name: mongo-express-valorizei
    image: mongo-express
    depends_on:
      - db-valorizei
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rpaiter
      ME_CONFIG_BASICAUTH_PASSWORD: rpaiter
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db-valorizei-mongodb
    links:
      - db-valorizei
    networks:
      - valoriza-network

  db-valorizei:
    container_name: db-valorizei-mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - "db_mongo:/data/db"
    networks:
      - valoriza-network

volumes:
  db_mongo:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/rpaiter/mongodb/valorizeidb/data'

networks:
  valoriza-network:
    driver: bridge

