apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app-valorizei
  name: app-valorizei
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app-valorizei
    spec:
      containers:
      - image: valoriza-api
        name: app-valorizei
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
