version: "3"

services:
  rabbitmq:
    container_name: rabbitmq-valorizei
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    networks:
      - valoriza-network

  mongo-express:
    container_name: mongo-express-valorizei
    image: mongo-express
    depends_on:
      - db-valorizei
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rpaiter
      ME_CONFIG_BASICAUTH_PASSWORD: rpaiter
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db-valorizei-mongodb
    links:
      - db-valorizei
    networks:
      - valoriza-network

  db-valorizei:
    container_name: db-valorizei-mongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - "db_mongo:/data/db"
    networks:
      - valoriza-network

  app-valorizei:
    container_name: app-valorizei
    image: valoriza-api
    depends_on:
      - db-valorizei
      - rabbitmq
    ports:
      - 9091:8080
    links:
      - db-valorizei
      - rabbitmq
    networks:
      - valoriza-network

volumes:
  db_mongo:
    #driver: local
    #driver_opts:
    #  type: 'none'
    #  o: 'bind'
    #  device: '/mongodb/data'

networks:
  valoriza-network:
    driver: bridge

