version: "3"

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: rpaiter
      ME_CONFIG_BASICAUTH_PASSWORD: rpaiter
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - db-valorizei
    networks:
      - valoriza-network

  db-valorizei:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - "db_mongo:/data/db"
    networks:
      - valoriza-network

  app-valorizei:
    image: valoriza-api
    ports:
      - 9091:8080
    links:
      - db-valorizei
    networks:
      - valoriza-network

volumes:
  db_mongo:
    #driver: local
    #driver_opts:
    #  type: 'none'
    #  o: 'bind'
    #  device: '/mongodb/data'

networks:
  valoriza-network:
    driver: bridge

